# Generated by Django 5.1.11 on 2025-06-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0002_alter_office_options_alter_office_table'),
        ('user', '0002_remove_user_username_user_typeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='user.user')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user.user')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['appointment_date'],
            },
        ),
    ]
