# Generated by Django 5.1.11 on 2025-06-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_id',
            new_name='id',
        ),
    ]
