# Generated by Django 5.1.11 on 2025-06-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
