# Generated by Django 5.1.11 on 2025-06-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['office_id']},
        ),
        migrations.AlterModelTable(
            name='office',
            table='offices',
        ),
    ]
