# Generated by Django 5.1.11 on 2025-06-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_office_options_alter_office_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='office',
            old_name='office_id',
            new_name='id',
        ),
    ]
