# Generated by Django 5.1.11 on 2025-06-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_is_active_remove_user_is_anonymous_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='encrypted_password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
