# Generated by Django 5.1.11 on 2025-06-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_encrypted_password_user_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
